---
key: "Produce_API-1.0.0"
name : "Produce_API"
displayName : "Produce_API"
description: "Sample API"
version: "1.0.0"
serviceUrl: "https://{MI_HOST}:{MI_PORT}/produce"
definitionType: "OAS3"
securityType: "BASIC"
mutualSSLEnabled: false
apiId : "null"
